In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/naukri_data_science_jobs_india.csv")

In [4]:
# Standardize column names
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

df.columns

Index(['company', 'location', 'education', 'skills_description', 'job_type',
       'salary', 'job_experience', 'job_role'],
      dtype='str')

In [5]:
quality_report = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Missing %": round((df.isnull().sum() / len(df)) * 100, 2),
    "Unique Values": df.nunique()
})

quality_report

                   Data Type  Missing Values  Missing %  Unique Values
company                  str               0       0.00           3507
location                 str               0       0.00            822
education                str            1676      13.97              6
skills_description       str               0       0.00          11356
job_type                 str            1280      10.67              2
salary               float64             976       8.13          10990
job_experience           str               0       0.00             30
job_role                 str               0       0.00           6563

In [6]:
# Fill missing values in categorical columns
df["education"] = df["education"].fillna("Not Specified")
df["job_type"] = df["job_type"].fillna("Not Specified")

# Check remaining missing values
df.isnull().sum()

company                 0
location                0
education               0
skills_description      0
job_type                0
salary                976
job_experience          0
job_role                0
dtype: int64

In [7]:
# Check all unique experience values
df["job_experience"].unique()

<StringArray>
['5-6', '1-7', '7-8', '6-7', '3-7', '2-4', '1-4', '3-4', '6-8', '3-5', '4-6',
 '1-3', '4-5', '4-7', '0-1', '0-2', '1-2', '5-7', '2-7', '2-3', '3-6', '0-7',
 '2-5', '1-6', '0-4', '0-6', '1-5', '2-6', '0-3', '0-5']
Length: 30, dtype: str

In [8]:
# Count each experience range
df["job_experience"].value_counts().sort_index()

job_experience
0-1     270
0-2     284
0-3     194
0-4     180
0-5     182
0-6     212
0-7     190
1-2     385
1-3     387
1-4     199
1-5     171
1-6     178
1-7     202
2-3     498
2-4     460
2-5     171
2-6     192
2-7     180
3-4     573
3-5     560
3-6     180
3-7     186
4-5     636
4-6     663
4-7     168
5-6     807
5-7     754
6-7     817
6-8     657
7-8    1464
Name: count, dtype: int64

In [9]:
# Split experience range into two columns
df[["exp_min", "exp_max"]] = df["job_experience"].str.split("-", expand=True)

# Convert to integers
df["exp_min"] = df["exp_min"].astype(int)
df["exp_max"] = df["exp_max"].astype(int)

# Create average experience column
df["exp_avg"] = (df["exp_min"] + df["exp_max"]) / 2

# Check the result
df[["job_experience", "exp_min", "exp_max", "exp_avg"]].head()

  job_experience  exp_min  exp_max  exp_avg
0            5-6        5        6      5.5
1            1-7        1        7      4.0
2            7-8        7        8      7.5
3            6-7        6        7      6.5
4            3-7        3        7      5.0